# compose file for a wordpress 
services:

  # nginx
  nginx:
  env_file: .env
  container_name: ${CONTAINER_NAME}-NGINX
  build:
    context: .
    dockerfile: nginx.Dockerfile
  restart: on-failure:3
  ports:
    - "8080:8080"
  volumes:
    # for linking wordpress and nginx
    - wordpress:/var/www/html:ro
    # for linking error-logs
    - ./nginx-logs:/tmp/nginx-logs
    # for linking access.log
    - ./nginx-logs:/var/log/nginx:rw   
  network:
    - ITSupport_network
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "nc", "-vz", "-w1", "localhost", "8080"]
    interval: 1s
    timeout: 1s
    retries: 30
  user: "www-data:www-data "
  
  # wordpress
  wordpress:
    env_file: .env
    container_name: ${CONTAINER_NAME}-WORDPRESS
    build:
      context: .
      dockerfile: wordpress.Dockerfile
    ports:
    - "9000:8080"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html:rw
      - wordpress:/bitnami/wordpress
    restart: on-failure:3
    network:
      - ITSupport_network
    user: "www-data:www-data "

  # database
  mariadb:
    env_file: .env
    container_name: ${CONTAINER_NAME}-DATABASE
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CONTAINER_NAME}-MARIADB
    ports:
      - "3306:3306"
    networks:
      - ITSupport_network
    volumes:
      - database:/var/lib/mysql

  # phpmyadmin section
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # remember to first create a user
    # in localhost:8081
    ports:
      - "8081:8080"
    networks:
      - internal
    restart: on-failure:3
    volumes:
      - phpmyadmin:/etc/phpmyadmin

volumes:
  nginx:
    driver: local
  wordpress:
    driver: local
  mariadb:
    driver: local
  phpmyadmin:
    driver: local

networks:
  ITSupport_network:
    driver: bridge
    attachable: true