services:
  # Database
  mariadb:
    container_name: ${CONTAINER_NAME}-DATABASE
    image: mariadb:latest
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - ITSupport_network
    restart: unless-stopped

  # WordPress
  wordpress:
    container_name: ${CONTAINER_NAME}-WORDPRESS
    build:
      context: .
      dockerfile: wordpress.Dockerfile
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html:rw
      # localfiles for php
      - /etc/shadow:/etc/shadow:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    depends_on:
      - mariadb
    networks:
      - ITSupport_network
    restart: unless-stopped
    # user 'nginx' in the group 'www-data'
    user: "nginx:www-data"

    tty: true
    command: tail -f /dev/null

  # Nginx
  nginx:
    container_name: ${CONTAINER_NAME}-NGINX
    build:
      context: .
      dockerfile: nginx.Dockerfile
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - wordpress:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/default.conf:ro
      - ./nginx/my_stream_server_block.conf:/etc/nginx/my_stream_server_block.conf:ro
      - ./nginx/wordpress-fpm:/etc/nginx/wordpress-fpm.conf:ro
      - ./nginx-logs:/var/log/nginx:rw
      
    depends_on:
      - wordpress
    networks:
      - ITSupport_network
    restart: unless-stopped

    tty: true
    command: tail -f /dev/null

  # phpMyAdmin
  phpmyadmin:
    container_name: ${CONTAINER_NAME}-PMA
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - ITSupport_network
    restart: unless-stopped

volumes:
  database:
  wordpress:

networks:
  ITSupport_network:
    driver: bridge