services:
  # Database
  mariadb:
    container_name: ${CONTAINER_NAME}-DATABASE
    image: mariadb:latest
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - database:/var/lib/mysql:rw
      # localfiles for php
      - /etc/shadow:/etc/shadow:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      - ITSupport_network
    restart: unless-stopped
    ports:
      -"${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:3306}:8000"


  # WordPress
  wordpress:
    container_name: ${CONTAINER_NAME}-WORDPRESS
    build:
      context: .
      dockerfile: wordpress.Dockerfile
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html:rw
      # localfiles for php
      - /etc/shadow:/etc/shadow:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    depends_on:
      - mariadb
    ports:
      -"${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:8080}:8000"
    networks:
      - ITSupport_network
    restart: unless-stopped
    # user 'nginx' in the group 'www-data'
    # user: "nginx:www-data"

    tty: true
    command: tail -f /dev/null

  # Nginx
  nginx:
    container_name: ${CONTAINER_NAME}-NGINX
    build:
      context: .
      dockerfile: nginx.Dockerfile
    env_file: .env
    ports:
      -"${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:80}:8000"
    volumes:
      - wordpress:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/default.conf:ro
      - ./nginx/my_stream_server_block.conf:/etc/nginx/my_stream_server_block.conf:ro
      - ./nginx/wordpress-fpm:/etc/nginx/wordpress-fpm.conf:ro
      - ./nginx-logs:/var/log/nginx:rw
      
    depends_on:
      - wordpress
    networks:
      - ITSupport_network
    restart: unless-stopped

    tty: true
    command: tail -f /dev/null

  # phpMyAdmin
  phpmyadmin:
    container_name: ${CONTAINER_NAME}-PMA
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      -"${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:8081}:8000"
    depends_on:
      - mariadb
    networks:
      - ITSupport_network
    restart: unless-stopped

  web:
    <<: *default-app
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8080/up}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

volumes:
  database: {}
  wordpress: {}
  phpmyadmin: {}
  mariadb: {}

networks:
  ITSupport_network:
    driver: bridge